name: Baisc Action Workflow

on:
  workflow_dispatch:
    
jobs:
  myfirst-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Stage-1
        run:  uname -a && data && p aux && sudo apt install tree || true && tree




