name: Email

on: 
  workflow_dispatch:

env:
  emails: "exmaple@gmail.com,exmaple2@gmail.com"

    


jobs:
  notify_on_fail: 
      runs-on: ubuntu-latest
      # needs: [ docker , Code-Check, Testing, SonarQube, Build]
      # if: ${{ needs.docker.result != 'success' }}
      if: ${{ failure() }}
      steps:
        - name: Send email
          uses: dawidd6/action-send-mail@v6
          with:
            server_address: smtp.gmail.com
            server_port: 587
            username: ${{ secrets.EMAIL_USER }}
            password: ${{ secrets.EMAIL_PASS }}
            subject: "❌ Build Failed  ${{ github.repository }}"
            to: ${{env.emails}}
            from: "GitHub Actions <noreply@example.com>"
            body: |
              ❌ Build Failed!

              • Pipeline: ${{ github.workflow }}
              • Job: ${{ github.job }}
              • Repository: ${{ github.repository }}
              • Branch: ${{ github.ref_name }}
              • Commit: ${{ github.sha }}
              • Commit Author: ${{ github.actor }}
              • Build Number: ${{ github.run_number }}
              • Run Attempt: ${{ github.run_attempt }}
              • Triggered By: ${{ github.event_name }}

              📝 Please review the logs & artifacts attached.

              👉 Open failed pipeline:
              ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            attachments: |
              trivy-results.sarif
              trivy_image_result.sarif

  Trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: ghcr.io/harshith6322/github-actions-ci-cd-project:latest
            format: 'sarif'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
            output: trivy_image_result.sarif

      - name: Trivy Check
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: "./"
          format: 'sarif'
          exit-code: 0
          output: "trivy-results.sarif"
        # run: cat -n trivy-results.sarif
      

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2.3.9
        with:
          fetch-depth: 0
          retention-days: 1



  sonar-qube:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5.0.0

      - name: Sonarqube Code Quality Analysis
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        with:
          projectBaseDir: .
          args: |
            -Dsonar.projectKey=newapp
            -Dsonar.sources=src
            -Dsonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
            -Dsonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

      - name:  QualityGate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
